### ISSUE TITLE
Questions/Feedback About Controls and Fungal Classification Considerations

### ISSUE THREAD

**Issue by cwarden45** [knightlab-analyses/mycobiome#1]
Hi,

Thank you very much for putting together this publication and associated resources (such as [http://cancermycobiome.ucsd.edu/](http://cancermycobiome.ucsd.edu/))!

I think this is more of a "discussion" than an "issue," but I don't think there is a separate discussion forum (either on GitHub or through the journal) and I think public discussion can be important.

I have some comments / questions where I hope that some feedback can be provided:

**1)** There was a Twitter discussion that I thought raised questions that might be relevant for readers to be aware of:

https://twitter.com/edhollox/status/1575553742757236736

If I understand correctly, I think the points from the Twitter discussion might not have been raised within the *“Limitations of the study.”* **For example, am I correctly understanding that the WIS extraction and paraffin controls were generated at a different time than the other WIS data?**  Or, do you think that I might have overlooked anything?

**2)** I thought it was interesting that previous studies like [Banerjee_et_al_2021](https://www.nature.com/articles/s41419-021-04092-x) were referenced.  However, if I am understanding correctly, are the exact associations reported different in earlier studies versus this study (such as a previous difference in abundance by grade versus a difference by age in this study)?  If you can reproduce previous findings, then I think that is encouraging.

At the same time, I also noticed that the publication indicates *“these analyses portray ubiquitous, low-abundance, cancer-type-specific mycobiomes that have community assemblies similar to those in adjacent normal tissues.”.*  As I understand it, I think there may be relevant tables of data between [Figures_data - Main_Figures]( https://github.com/knightlab-analyses/mycobiome/tree/master/Figures_data/Main_Figures) and [Final_files]( https://github.com/knightlab-analyses/mycobiome/tree/master/Final_files).  Additionally, in terms of the data used for **Figure 6A**, I believe that **Table S2.3** provided a relevant table?

If so, I have created plots below for **fid1723g** (for **Cladosporium**):

![Cladosporium-box](https://user-images.githubusercontent.com/7663033/196785279-1ded70bf-ce07-42a1-8df0-f3e673799307.png)

While I think the full data and continuous abundance (for a given processing strategy) is important, I think assigning a status when abundance is greater than a threshold (such as 1%) might also be helpful when trying to visualize trends when a subset of the total samples show the change in fungal abundance:

![Cladosporium-bar](https://user-images.githubusercontent.com/7663033/197361720-a56e7aaf-9cf6-45a8-8b24-e3f6825b0743.png)

**Do you think this relates to any important caveats for interpretation of the data for this publication?**

If it might help, then you can also see the code that I used to create those plots below:

```
input.table1 = read.delim("../1-s2.0-S0092867422011278-mmc2-Table S2.3.txt")
SampleID = names(input.table1)[10:ncol(input.table1)]
Tissue = as.character(input.table1[1,10:ncol(input.table1)])
Type = as.character(input.table1[2,10:ncol(input.table1)])
PatientID = as.character(input.table1[12,10:ncol(input.table1)])
Age = as.numeric(as.character(input.table1[13,10:ncol(input.table1)]))
TotalNormalizedReads = as.numeric(as.character(input.table1[22,10:ncol(input.table1)]))

patient.counts = table(PatientID[TotalNormalizedReads != 0])
pairedID = names(patient.counts)[patient.counts == 2]

filteredID = SampleID[(Tissue == "breast")&(PatientID %in% pairedID)]

input.table = read.delim("../1-s2.0-S0092867422011278-mmc2-Table S2.3.txt", skip=24, head=T)
matchedIDs = names(input.table)[match(filteredID,names(input.table), nomatch=0)]
matchedType = Type[match(matchedIDs, SampleID)]
matchedPatientID = PatientID[match(matchedIDs, SampleID)]
matchedAge = Age[match(matchedIDs, SampleID)]
matchedTotalNormalizedReads = TotalNormalizedReads[match(matchedIDs, SampleID)]

count.mat = input.table[,match(matchedIDs,names(input.table))]
rownames(count.mat) = input.table$fid

ab.mat = count.mat
for (i in 1:ncol(ab.mat)){
	ab.mat[,i] = signif(100 *count.mat[i]/matchedTotalNormalizedReads[i], 4) 
}#end for (i in 1:ncol(ab.mat))

Cladosporium.ab = as.numeric(ab.mat[rownames(ab.mat) == "fid1723g",])
plotCat = rep(NA,ncol(ab.mat))
plotCat[(matchedType == "tumor")&(matchedAge > 50)] = "Cancer - greater than 50"
plotCat[(matchedType == "tumor")&(matchedAge <= 50)] = "Cancer - less than or equal to 50"
plotCat[(matchedType == "nat")&(matchedAge > 50)] = "Adjacent Normal - greater than 50"
plotCat[(matchedType == "nat")&(matchedAge <= 50)] = "Adjacent Normal - less than or equal to 50"
plotCat = factor(plotCat,
		levels = c("Adjacent Normal - less than or equal to 50", "Cancer - less than or equal to 50",
							"Adjacent Normal - greater than 50", "Cancer - greater than 50"))

png("Cladosporium-box.png")
par(mar=c(18,5,3,2))
plot(plotCat, Cladosporium.ab, xlab="", las=2, ylab="Normalized Abundance")
dev.off()

Cladosporium.status = rep(0,ncol(ab.mat))
Cladosporium.status[Cladosporium.ab > 1]=1

png("Cladosporium-bar.png")
par(mar=c(18,5,5,2))
barplot(table(Cladosporium.status, plotCat),
		las=2, col=c("black","red"), ylab="Sample Count")
legend("top", legend=c(">1% Normalized Abundance","Lower Abundance"),
		col=c("red","black"), ncol=2, pch=15, xpd=T, inset = -0.25)
dev.off()
```
**NOTE:** I edited the y-axis for the barplot on 10/22/2022.

Thank you very much!

Sincerely,
Charles

**Comment by ilivyatan** [comment]
[2022-10-20_Answer_for_GitHub_IL.docx](https://github.com/knightlab-analyses/mycobiome/files/9837018/2022-10-20_Answer_for_GitHub_IL.docx)

**Comment by cwarden45** [comment]
Thank you very much for your response!

As I was re-reading my post and reading your response, I noticed that I needed to fix the label for the y-axis for a plot.  I apologize about that.  I have fixed the plot and associated code, and I added a note (in addition to the automatic tracked history for GitHub).

In terms of additional responses:

**1)** I did not come up with the ideas for this part, but I was interested in the conversation that I saw among others.  I think the issue might not have been whether those 2 controls were run at the same time, versus if those controls were run at the same time as other previously published samples (such as the cancer samples).  I apologize that I am not 100% certain if this is what you are saying in the response, but I see that there are *dna.extraction.batch*, *PCR batch*, *Batch dilution factor*, and *Sequencing batch* variables in the Supplemental Table (also used for the other analysis).

If I use the code below (**added to the original code**), I don’t think the controls cover all of the combinations of batch effects:

```
dna.extraction.batch = as.character(input.table1[7,10:ncol(input.table1)])
PCR.batch = as.character(input.table1[8,10:ncol(input.table1)])
Batch.dilution.factor = as.character(input.table1[9,10:ncol(input.table1)])
Sequencing.batch = as.character(input.table1[10,10:ncol(input.table1)])

TotalBatch = paste(dna.extraction.batch,PCR.batch,Batch.dilution.factor,Sequencing.batch,sep=":")
print(dim(table(TotalBatch)))
batch_type_table = table(TotalBatch, Tissue)
print(dim(batch_type_table))
control_counts = batch_type_table[,"control"]
print(length(control_counts[control_counts != 0]))
```
However, I will mention this posting in the original Twitter thread, and I will see if this helps with addressing the questions raised by others.  **For example, I don’t know if this might cover more conditions than originally expected.**

There are also **Sample ID bacterial project** and **Center** variables, but I am not sure if I am confused about those.  For example, there are a lot of different **Sample ID bacterial project** values.  Also, while all other batches are the same, the first two samples (*F0010* and *F0011*) have different center values (**sheba** and **control**).

Either way, thank you again for the response!

**2a)** Thank you for pointing out that there is a relevant Dohlmen et al. reference.  It looks like [Dohlmen et al. 2021]( https://www.cell.com/cell-host-microbe/fulltext/S1931-3128(20)30663-6) from *Cell Host and Microbe* is relevant for this discussion.  If the “IL” in the uploaded file name stands for *“Ilana Livyatan”* (which I think also matches the [ilivyatan]( https://github.com/ilivyatan) GitHub account), then I didn’t see anything in PubMed for a search with *“Anders Dohlman AND Ilana Livyatan”* or for *“Anders Dohlman AND (Rob Knight OR Ravid Straussman)”*.  So, if there was a different reference in mind, then I would certainly appreciate that information.

As I was reading through the details in your response, I noticed the following:
 - It might have been helpful for me to provide a link to the [Narunsky-Haziza et al. 2022]( https://www.sciencedirect.com/science/article/pii/S0092867422011278) publication, as a convenience for anyone who starts to learn more about the paper from this discussion.
 - I needed to **delete the first row** for the header to use the code for re-analysis of the exported tab-delimited text file from **Table S2** (for the sheet containing **Table S2.3**).  So, I hope that helps if anybody otherwise has difficulty reproducing the results from the code.

Also, I noticed the sentence referenced in the [Narunsky-Haziza et al. 2022]( https://www.sciencedirect.com/science/article/pii/S0092867422011278) publication.  However, when I went back to the [Banerjee_et_al_2021](https://www.nature.com/articles/s41419-021-04092-x), I noticed that *Figure 5B* shows a difference with grade.  I am not sure if I might still be overlooking something from that publication, but I didn’t find a claim related to age when searching for “50” in the main text.

**2b)** When I choose a threshold of 1% for visualization, I don’t assign statistical significance.  However, there is some qualitative increase in the older cancer sample over the older adjacent normal.

However, at the same time, I believe that means that analysis only using the tumor samples without trying to take the adjacent normal samples into consideration will inflate the significance of the result.  **So, I think some sort of use of the *adjacent normal samples* is important.**

In terms of trying to explain my strategy more, I essentially noticed a large difference between values less than 1% and all other values (in addition to expecting a large number of small values could make the box-plots misleading/confusing):

![hist2](https://user-images.githubusercontent.com/7663033/197363598-7121e0bc-a6ed-4bcc-abb7-7b0d64e5f8ee.png)

The above plot was created from originally noticing a large difference for values above and below 10% (not directly shown here).

If looking for something causal, I think a more stringent filter for abundance makes sense.  However, the paper says *“although our study broadens the cancer microbiome landscape, our findings do not establish causality”.*

In the event that binning strategy missed another large difference below 1%, I recalculated abundance values with different rounding.  However, all values less than 1% were still equal to zero.  So, perhaps it would be good if I can take some time to better understand the “flooring” method used in this paper.

Either way, if helpful, here is the code for the above plot and attempt to provide a revised bar plot:

```
print(table(Cladosporium.status, plotCat))

png("hist2.png")
hist(Cladosporium.ab[Cladosporium.ab < 10])
dev.off()

ab.mat = count.mat
for (i in 1:ncol(ab.mat)){
	ab.mat[,i] = signif(100 *count.mat[i]/matchedTotalNormalizedReads[i], 6) 
}#end for (i in 1:ncol(ab.mat))

print(table(Cladosporium.ab[Cladosporium.ab < 1]))
```

In the earlier bar-plot, there were 30 cancer samples older than 50 with *Cladosporium* and 38 samples without *Cladosporium*.  For the adjacent normal samples, the counts were 18 with *Cladosporium* and 50 without *Cladosporium*.  **So, among older individuals, that would be a frequency of 44.1% in the older cancer samples and 26.5% in the older adjacent normal samples.**

I believe that is higher than the prevalence reported in **Figure 6B** (which might include unpaired cancer samples?), but that also represents an increase in the adjacent normal.  So, I don’t know how the overall significance is affected when both of those are carefully taken into consideration.

**In other words, I agree that I am not contradicting the exact point for *Cladosporium*, but there could be other situations where the cancer difference is more similar to the normal tissue difference.**

**3)** I hope it is a minor point, but I was not sure if there was something relevant about posting a Word document.

So, to try and explain myself a bit better, I think public discussion after any sort of publication is important but I am trying to also take the perspectives of the authors into consideration.

For example, [this]( https://www.nature.com/articles/s41598-019-42455-9#article-comments) is one of the more involved journal-based “comment system” discussions.  However, I did not believe I saw that as an option for this paper.

I guess the GitHub markdown format can add some barriers to entry.  However, my understanding is that posting on PubPeer can have a negative connotation.

I am not sure if part of the basis for believing pubic discussion is important relates to the importance for software support (such as [here]( https://sourceforge.net/p/cohcap/discussion/) or [here]( https://github.com/cwarden45/COHCAP/issues)).  However, as both a developer and a user, I have found this very helpful.  Even if there is misunderstanding, I might have the same misunderstanding and having an existing link can be important.

Nevertheless, if anything about my rationale is not clear and/or the method of communication can improve, then I would certainly appreciate feedback/discussion to consider in the future.

Consistent with other situations where I have used this as forum of discussion, I am now closing the "ticket" to acknowledge your helpful response.  However, I certainly still welcome any possible further feedback.

Again, thank you very much!

Sincerely,
Charles

**Comment by ilivyatan** [comment]
Hi Charles,

Thank you for your interest and questions. Despite the "ticket" being closed, you raised a couple points that we felt could be further clarified.

1.       The extraction controls were processed together with the tissue samples- each sample batch included several extraction controls. The samples used here are mostly a subset of the samples used in [Nejman et al. 2020](https://pubmed.ncbi.nlm.nih.gov/32467386/) (please refer to this paper for full details on the way the samples and controls were processed). We also randomly selected a subset of the DNA extraction controls from the same batches from which our samples were derived. All of the PCR batches and sequencing batches that we had in the study, include relevant extraction controls. For the paraffin controls - these came from paraffin from the same blocks of the tissue samples that were used for the study. They control for contaminations entered during handling in the medical centers. Since the paraffin controls were added at a later time, the DNA extraction of these samples was done in separate batches. However they were used in PCR batches with our tumor samples and the sequencing run included both tissue and all types of controls. More importantly, we included all of the batches data in our sup tables and you should be able to explore it in much detail.

The sample ID bacterial project- refers to the Sample ID from [Nejman et al. 2020](https://pubmed.ncbi.nlm.nih.gov/32467386/). The center refers to the hospital from which we received the samples.

Sheba is a hospital in Israel. 
The extraction controls received a “control” entry in the center column as they were created in our lab.

2B.       With regard to figure 6A- this DOES include also tumor samples with no matched NAT sample. And as you point out the status of Cladosporium in NAT samples does not affect the finding reported in 6A or the claim that tumor and NAT have similar fungal profiles. I do agree that the fungi in NAT samples and the relation to the fungi found in matching tumors is of great interest and deserves further investigation.

Hope this is helpful for you and others.

**Comment by ilivyatan** [comment]
Thank you for your interest and questions. Despite the "ticket" being closed, we wanted to add some additional clarifications given some of your additional questions:

1. The extraction controls were processed together with the tissue samples- each sample batch included several extraction controls. The samples used here are mostly a subset of the samples used in [Nejman et al. 2020](https://pubmed.ncbi.nlm.nih.gov/32467386/) (please refer to this paper for full details on the way the samples and controls were processed). We also randomly selected a subset of the DNA extraction controls from the same batches from which our samples were derived. All of the PCR batches and sequencing batches that we had in the study, include relevant extraction controls. For the paraffin controls - these came from paraffin from the same blocks of the tissue samples that were used for the study. They control for contaminations entered during handling in the medical centers. Since the paraffin controls were added at a later time, the DNA extraction of these samples was done in separate batches. However they were used in PCR batches with our tumor samples and the sequencing run included both tissue and all types of controls. More importantly, we included all of the batches data in our sup tables and you should be able to explore it in much detail.

The sample ID bacterial project- refers to the Sample ID from [Nejman et al. 2020](https://pubmed.ncbi.nlm.nih.gov/32467386/). 
The center refers to the hospital from which we received the samples.

Sheba is a hospital in Israel. 
The extraction controls received a “control” entry in the center column as they were created in our lab.

2B. In regard to figure 6A- this DOES include also tumor samples with no matched NAT sample. And as you point out the status of Cladosporium in NAT samples does not affect the finding reported in 6A or the claim that tumor and NAT have similar fungal profiles. I do agree that the fungi in NAT samples and the relation to the fungi found in matching tumors is of great interest and deserves further investigation.

Hopefully this helps you and others.

**Comment by cwarden45** [comment]
Thank you very much for your additional response!

As I understand it, I think the adjacent normal tissue samples might partially act as both biological and technical controls, as long as you are trying to characterize something related to the cancer tissue/cells.

At this moment, I am not sure if something could potentially be systemically misclassified (so what appears to be a particular fungus might in fact be something else that is changing).  In other words, I think some extra work might be helpful to assess the normal differences in the adjacent normal samples.  However, I am not sure if that might also be at least somewhat matching what you are saying about studying the adjacent normal samples more in the future.

Either way, it would probably be good for me to read more details from the [Nejman et al. 2020](https://pubmed.ncbi.nlm.nih.gov/32467386/) study.

Thank you again!
